version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    labels:
      - "com.example.container_id=prometheus"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    privileged: true
    ports:
      - "8082:8080"
    networks:
      - monitoring-net
    labels:
      - "com.example.container_id=cadvisor"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg:ro
    devices:
      - /dev/kmsg
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
      - cicd-net
    labels:
      - "com.example.container_id=grafana"
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
  stress:
    image: progrium/stress
    container_name: stress
    command: ["--cpu", "8", "--vm", "3", "--vm-bytes", "1G", "--timeout", "600"]
    profiles:
      - stress-test
    networks:
      - monitoring-net

networks:
  monitoring-net:
  cicd-net:
    
volumes:
  prometheus-data:
  grafana_data: 
