global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [container_label_com_docker_compose_service]
        target_label: container
      - source_labels: [container_name]
        target_label: instance

